name: 🚀 Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CI: true
  NODE_VERSION: 16

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx changelogithub --draft
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
